### ISSUE TITLE
Zookeeper数据管理器及curator封装核心包

### ISSUE THREAD

**Issue by SevenMeteor** [521xueweihan/HelloGitHub#1110]
## 项目推荐 Meteor-zookeeper
- 项目地址：https://github.com/SevenMeteor/meteor-zookeeper
- 类别：JAVA、Zookeeper 

- 项目后续更新计划：
     - 优化前端节点过多vue渲染问题
     - 引入db为提供节点备注信息。

- 项目描述： 
  # 主要功能
       提供可视化页面用于管理Zookeeper的资源节点。
      对curator封装，在项目代码 、xml配置中可以获取Zookeeper的配置信息。
  # 适用场景
       不同环境配置管理。
       项目引用zookeeper配置，甚至利用zk特性更好的实现事务锁 
- 推荐理由： 对于拥有多环境配置及多配置信息，需要使用到zookeeper的人，又不想引入过大的程序

- 截图：
![image](https://user-images.githubusercontent.com/31543180/75599635-c8217a00-5ae1-11ea-9809-4eaa20cea610.png)

![image](https://user-images.githubusercontent.com/31543180/75599617-b0e28c80-5ae1-11ea-909a-4eaa4b4d3441.png)

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
