### ISSUE TITLE
【自荐】libhv：一个类似libevent、libev、libuv的跨平台异步IO库

### ISSUE THREAD

**Issue by ithewei** [521xueweihan/HelloGitHub#1121]
`##` 项目推荐
- 项目地址：https://github.com/ithewei/libhv.git

- 类别：C、C++

- 项目后续更新计划：
实现更多的协议，如websocket、MQTT、Redis等；

- 项目描述：
  - 一个类似libevent、libev、libuv的跨平台异步IO库；
  - 可方便用来编写HTTP API客户端/服务端 ；
  - libhv提供的httpd服务性能可媲美nginx；

- 推荐理由：比libevent、libuv更简单易用，实现了更多的常见协议，如http、ftp、dns、smtp等；

- 示例代码：
```
#include "HttpServer.h"

int http_api_echo(HttpRequest* req, HttpResponse* res) {
    res->body = req->body;
    return 0;
}

int main() {
    HttpService service;
    service.base_url = "/v1/api";
    service.AddApi("/echo", HTTP_POST, http_api_echo);

    http_server_t server;
    server.port = 8080;
    server.service = &service;
    http_server_run(&server);
    return 0;
}
```

- 截图：
[libhv vs nginx](https://github.com/ithewei/libhv/blob/master/html/downloads/libhv-vs-nginx.png)
[echo servers](https://github.com/ithewei/libhv/blob/master/html/downloads/echo-servers.jpg)

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 48 期](https://hellogithub.com/periodical/volume/48/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
