### ISSUE TITLE
【开源项目】 Milvus 向量检索引擎

### ISSUE THREAD

**Issue by kateshaowanjou** [521xueweihan/HelloGitHub#1127]
## 项目推荐
- 项目地址：https://github.com/milvus-io

- 类别：请从中选择（开发语言C++、另支持 JAVA & Python SDK）

- 项目后续更新计划：目前版本0.6.0， v0.7.0 2020 3月

- 项目描述：
  - 必写：Milvus 是一款开源的、针对海量特征向量的相似性搜索引擎。基于异构众核计算框架设计，成本更低，性能更好。 在有限的计算资源下，十亿向量搜索仅毫秒响应。Milvus 能够广泛应用于各种 AI 场景，为 AI 发展提供有效助力。
  - 可选：不需要是数据科学家也可以搭建自己的AI应用
  - 描述长度（不包含示例代码）: 10 - 256 个字符
1. 图片识别：以图搜图，通过图片检索图片。具体应用例如：车辆检索和商品图片检索等。
2. 视频处理：针对视频信息的实时轨迹跟踪
3. 自然语言处理：基于语义的文本检索和推荐，通过文本检索近似文本。
4. 声纹匹配，音频检索。
5. 文件去重，通过文件指纹去除重复文件。

- 推荐理由：相比 Faiss 和 SPTAG 这样的算子库，Milvus 提供完整的向量数据更新，索引与查询框架。Milvus 利用 GPU 进行索引加速与查询加速，能大幅提高单机性能。Milvus 向量搜索引擎可以广泛地和各种深度学习模型进行整合，简化 AI 应用落地的难度。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![截屏2020-03-09上午10 04 13](https://user-images.githubusercontent.com/58837504/76177088-03146380-61ee-11ea-96af-4bfb051a3c6a.png)

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 48 期](https://hellogithub.com/periodical/volume/48/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
