### ISSUE TITLE
gin框架自动注册路由,自动文档生成插件

### ISSUE THREAD

**Issue by xxjwxc** [521xueweihan/HelloGitHub#1136]
## 项目推荐
- 项目地址：https://github.com/xxjwxc/ginrpc

- 类别：Go

- 项目后续更新计划：
- 服务注册与发现

- 项目描述：
简化go-gin框架注册路由方式，自动生成swagger/markdown文档，可以让初学者一分钟构建一套完整grpc/web http 务框架。

支持对象自动注册及注解路由
支持参数自动绑定
自带请求参数过滤及绑定实现 binding:"required" validator
支持 grpc 绑定模式
支持swagger 文档导出
支持markdown/mindoc 文档导出
支持grpc/restful 访问方式

- 推荐理由：web/ rpc 框架，解放重复繁杂路由绑定工作。文档自动导出

- 示例代码：（可选）
```
type ReqTest struct {
	UserName    string `json:"user_name" binding:"required"` // 带校验方式
}

type Hello struct {
}

// Hello [grpc-go](https://github.com/grpc/grpc-go) 模式
// @Router /hello_ruter [post,get]
func (s *Hello) Hello(c *gin.Context, req ReqTest) (*ReqTest, error) {
	fmt.Println(req)
	return &req,nil
}

func main() {
	base := ginrpc.New(ginrpc.WithGroup("xxjwxc"))
	router := gin.Default()
	base.Register(router, new(Hello)) // 对象注册 like(go-micro)
	router.Run(":8080")
}
```

- 截图：

![11](https://user-images.githubusercontent.com/9114492/76700375-bc44d300-66f1-11ea-97e2-34d7669fd80a.gif)

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
