### ISSUE TITLE
generator-jhipster

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#1156]
## 项目推荐
- 项目地址：https://github.com/jhipster/generator-jhipster

- 类别：Java
- 项目后续更新计划：

- 项目描述：
  - 必写：springboot的开源项目，可快速构建前后端分离的项目，前端可选VUE,React,Angular等多种语言。
  - 可选：按照教程操作,可快速入门，实现全栈开发。
  - 描述长度（不包含示例代码）: 项目在持续更新和维护中。

- 推荐理由：开源应用程序平台，可在几秒钟内创建Spring Boot + Angular / React项目！

- 示例代码：（可选）长度：1-20 行

```
1. Install JHipster npm install -g generator-jhipster
2. Create a new directory and go into it mkdir myApp && cd myApp
3. Run JHipster and follow instructions on screen jhipster
4. Model your entities with JDL Studio and download the resulting jhipster-jdl.jh file
5. Generate your entities with jhipster import-jdl jhipster-jdl.jh
```

- 截图：（可选）gif/png/jpg

![](https://repository-images.githubusercontent.com/13753636/d2cb6600-8b84-11e9-84ea-5ff54bd24e9c)

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by 521xueweihan** [comment]
该项目已推荐过
