### ISSUE TITLE
[自荐]kafka一站式平台KafkaCenter

### ISSUE THREAD

**Issue by TrumanDu** [521xueweihan/HelloGitHub#1157]
## 项目推荐
- 项目地址：
https://github.com/xaecbd/KafkaCenter
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
Java
- 项目后续更新计划：

- 项目描述：
  - 必写：KafkaCenter是Kafka 集群管理和维护，生产/消费监控，生态组件使用的统一一站式平台。
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
  - **统一:** 一个平台，一站式包含自助，管理，监控，运维，使用一体化。
  - **流程化:** 创建topic流程化，做到对topic使用全生命周期管理。
  - **复用:** 平台支持接入多个集群，复用性很高。
  - **成本:** 只用部署一套程序，节省机器资源。降低运维成本，高效运维。
  - **生态:** 目前已经接入connect，ksql。
  - **便捷:** 提供便捷工具，让无需有kafka使用经验的人，都可以方便生产、消费消息。
  - **全局:** 可以站在不同的维度查看目前kafka使用情况
  - **权限:** 完善的权限设计，减少风险漏洞。
- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![](http://blogstatic.aibibang.com/screenshot.png)
![](http://blogstatic.aibibang.com/kafka-center.png)

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 48 期](https://hellogithub.com/periodical/volume/48/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
