### ISSUE TITLE
项目推荐 | AuthPass 基于 Flutter 开发的全平台密码管理器

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1841]
## 项目推荐
- 项目地址：https://github.com/authpass/authpass

- 类别：Flutter、其他

- 项目后续更新计划：未来会支持自定义的云同步源，支持 IOS 系统的密码填充等更多功能

- 项目描述：适用于所有平台的基于 Flutter 的密码管理器

- 推荐理由：支持全平台，支持 Dropbox 或 Google Drive 等云服务同步，支持 Android 上自动填充密码

- 截图：
![image](https://user-images.githubusercontent.com/38283893/129333633-cdb157a6-a1e7-4110-8900-1792921b2eca.png)

**Comment by learningintheworld** [comment]
有病吧一直发





------------------ 原始邮件 ------------------
发件人: 削微寒 ***@***.***&gt;
发送时间: 2021年8月23日 11:29
收件人: 521xueweihan/HelloGitHub ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[521xueweihan/HelloGitHub] 项目推荐 | AuthPass 基于 Flutter 开发的全平台密码管理器 (#1841)





 
Closed #1841.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SekiBetu** [comment]
> 有病吧一直发
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 削微寒 ***@***.***&gt; 发送时间: 2021年8月23日 11:29 收件人: 521xueweihan/HelloGitHub ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[521xueweihan/HelloGitHub] 项目推荐 | AuthPass 基于 Flutter 开发的全平台密码管理器 (#1841) Closed #1841. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

![image](https://user-images.githubusercontent.com/38283893/130386318-6735d1c2-52c7-4168-b719-d45b454459c3.png)
你是不是点了watch All activity了，换成如图就不会经常发邮件过来了

**Comment by learningintheworld** [comment]
好哒谢谢





------------------ 原始邮件 ------------------
发件人: 惜别 ***@***.***&gt;
发送时间: 2021年8月23日 11:31
收件人: 521xueweihan/HelloGitHub ***@***.***&gt;
抄送: learningintheworld ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[521xueweihan/HelloGitHub] 项目推荐 | AuthPass 基于 Flutter 开发的全平台密码管理器 (#1841)





  
有病吧一直发
 …
 ------------------ 原始邮件 ------------------ 发件人: 削微寒 @.&gt; 发送时间: 2021年8月23日 11:29 收件人: 521xueweihan/HelloGitHub @.&gt; 抄送: Subscribed @.***&gt; 主题: 回复：[521xueweihan/HelloGitHub] 项目推荐 | AuthPass 基于 Flutter 开发的全平台密码管理器 (#1841) Closed #1841. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  

 你是不是点了watch All activity了，换成如图就不会经常发邮件过来了
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
