### ISSUE TITLE
【开源自荐】MagicMirror 一键 AI 换脸、发型、穿搭，发现更美的自己 ✨

### ISSUE THREAD

**Issue by idootop** [521xueweihan/HelloGitHub#2859]
## 推荐项目

- 项目地址：https://github.com/idootop/MagicMirror

- 类别：机器学习

- 项目标题：一键 AI 换脸、发型、穿搭，发现更美的自己

- 项目描述：一个极简的 AI 换脸项目，拥有最简单直观的交互界面，最精简的代码和安装包体积，如果你想要快速了解或体验 AI 换脸技术，这个项目会是你的最佳选择之一。

- 亮点：
    - 一键换脸：打开安装包，拖张照片进去就能换脸，无需配置各种复杂参数。
    - 超低门槛：不用 GPU 也能运行，普通的小白电脑也可以轻松玩转 AI 换脸。
    - 隐私安全：完全在你的电脑本地运行，不需要联网，不用担心你的图片会被上传到任何地方。
    - 极致精简：安装包不到 10 MB，模型文件加起来不到 1 GB，这可能是最轻量的离线换脸应用之一。

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

![](https://github.com/idootop/MagicMirror/raw/main/docs/assets/demo.webp)

![demo](https://github.com/user-attachments/assets/b3b52898-4d43-40db-8fbe-acbc00d78eec)

- 后续更新计划：目前已经发布 v1.0 稳定版本，后续根据反馈维护更新

**Comment by 521xueweihan** [comment]
@idootop 你好，[MagicMirror](https://github.com/idootop/MagicMirror) 将收录到下期月刊中，发布后将在此 issues 上通知。

另外，我看你头像很眼熟，才发现你的另一个项目已被 hellogithub 社区收录，不知道能否邀请你[认领](https://hellogithub.com/repository/e02e62fbb9c746cdb61c6559c186ac44) mi-gpt，再次感谢您的支持和分享。

**Comment by idootop** [comment]
@521xueweihan 已提交认领

**Comment by 521xueweihan** [comment]
@idootop 感谢支持～

<img width="743" alt="image" src="https://github.com/user-attachments/assets/cbe0e1ee-792a-4f74-9f39-d9d732b58cd0">

**Comment by 521xueweihan** [comment]
@idootop 我本地试了一下（Apple M2），手动下载模型，启动等待超过 10 分钟无反应。
<img width="690" alt="image" src="https://github.com/user-attachments/assets/55da89c8-f6f4-460f-b2a5-379bff5bb894" />

**Comment by idootop** [comment]
@521xueweihan M1 一切正常，在我测试过的 Windows/macOS 设备中都能正常运行。

确保你下载的 server 架构和你的芯片相符，以及授予 server.bin 可运行权限（理论上会自动处理权限）。

<img width="920" alt="图片" src="https://github.com/user-attachments/assets/7a08a846-2c38-421e-91e1-c9c54a6e83cf" />

正常启动成功，浏览器访问 http://localhost:8023 能够看到 MagicMirror 的提示，你可以检查下。

<img width="524" alt="图片" src="https://github.com/user-attachments/assets/1e8e0283-a07f-4fdd-8f67-45f707f043dd" />

**Comment by 521xueweihan** [comment]
@521xueweihan 
1. 我的操作系统为 13.0 (22A380)
2. 模型下载的是 server_macos_aarch64.zip
3. 但浏览器访问 http://localhost:8023/ 失败，服务没起起来

![image](https://github.com/user-attachments/assets/8dd2075e-ff1d-4981-aebd-6ef60e6537fd)

**Comment by idootop** [comment]
你可以手动在命令行运行下，看看有没有报错

<img width="522" alt="图片" src="https://github.com/user-attachments/assets/5def3fce-3b9d-4a10-af0b-831c2b778d1f" />

**Comment by 521xueweihan** [comment]
![image](https://github.com/user-attachments/assets/2367a6f3-e898-43b9-8c8f-19403c910a65)

@idootop 我查了下，异常原因可能是：当前安装的 NumPy 包是为比你的当前 macOS 系统更高的版本（macOS 14.0 或 Sonoma）编译的，而你的系统是旧版本（比如 macOS 12 或 13）。因此发生了符号找不到的错误。


➜  MagicMirror ./server.bin
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
Traceback (most recent call last):
  File "/Users/xueweihan/MagicMirror/numpy/_core/__init__.py", line 23, in <module numpy._core>
  File "/Users/xueweihan/MagicMirror/numpy/_core/multiarray.py", line 10, in <module numpy._core.multiarray>
  File "/Users/xueweihan/MagicMirror/numpy/_core/overrides.py", line 8, in <module numpy._core.overrides>
ImportError: dlopen(/Users/xueweihan/MagicMirror/numpy/_core/_multiarray_umath.so, 0x0002): Symbol not found: _cblas_caxpy$NEWLAPACK$ILP64
  Referenced from: <AA63688C-5234-369A-AB79-9693F439579D> /Users/xueweihan/MagicMirror/numpy/_core/_multiarray_umath.so (built for macOS 14.0 which is newer than running OS)
  Expected in:     <E6C2D470-8878-372D-B9DB-0EDCA1303272> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xueweihan/MagicMirror/numpy/__init__.py", line 114, in <module numpy>
  File "/Users/xueweihan/MagicMirror/numpy/__config__.py", line 4, in <module numpy.__config__>
  File "/Users/xueweihan/MagicMirror/numpy/_core/__init__.py", line 49, in <module numpy._core>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Users/xueweihan/MagicMirror/python"
  * The NumPy version is: "2.1.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/xueweihan/MagicMirror/numpy/_core/_multiarray_umath.so, 0x0002): Symbol not found: _cblas_caxpy$NEWLAPACK$ILP64
  Referenced from: <AA63688C-5234-369A-AB79-9693F439579D> /Users/xueweihan/MagicMirror/numpy/_core/_multiarray_umath.so (built for macOS 14.0 which is newer than running OS)
  Expected in:     <E6C2D470-8878-372D-B9DB-0EDCA1303272> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xueweihan/MagicMirror/server.py", line 1, in <module>
  File "/Users/xueweihan/MagicMirror/magic/app.py", line 6, in <module magic.app>
  File "/Users/xueweihan/MagicMirror/magic/face.py", line 4, in <module magic.face>
  File "/Users/xueweihan/MagicMirror/cv2/__init__.py", line 11, in <module cv2>
  File "/Users/xueweihan/MagicMirror/numpy/__init__.py", line 119, in <module numpy>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

**Comment by idootop** [comment]
@521xueweihan 哈哈，多谢反馈 👍 后面我加到 FAQ 里面去。

针对这个问题，MagicMirror server 端目前是在 Github Action 自动编译，暂不考虑对低版本的兼容。

后面有时间我再研究研究 Python 打包 numpy 的问题，让其兼容更多设备。

**Comment by 521xueweihan** [comment]
@idootop 好的，我理解这个是个一键换脸应用，具体换装和发型，是不是也是通过换脸实现，不是可以上传发型之类的。

**Comment by idootop** [comment]
是的，纯换脸。这里有相关视频介绍：https://www.bilibili.com/video/BV1TTzfYDEUe

想要更好的人脸融合效果，以及人物换装/试穿就得上 sd、flux 之类的大模型了，对本地 GPU 硬件要求较高。

**Comment by 521xueweihan** [comment]
@idootop 收到

**Comment by idootop** [comment]
> @idootop 我本地试了一下（Apple M2），手动下载模型，启动等待超过 10 分钟无反应。 

@521xueweihan 更新了一版，现在可以在 macOS 13 上运行了。

https://github.com/idootop/MagicMirror/releases/tag/server-v2.0.0

PS：第一次启动大概需要 3-5 分钟，如果弹窗提示打开“xxx”失败，需要手动设置下信任任何来源（我没签名）。

**Comment by 521xueweihan** [comment]
@idootop 忘了说了 MagicMirror 已收录，https://hellogithub.com/repository/idootop/MagicMirror

欢迎认领哈：https://hellogithub.com/badge?rid=9d0e987477ea433a9079f6d27a22202f
